### ISSUE TITLE
Wiped out Local book marks.

### ISSUE THREAD

**Issue by jasonkuehl** [mjanser/firefox-addon-owncloud-bookmarks#1]
Something I noticed after I did my sync it added my owncloud bookmarks folder but it wiped out all my local bookmarks in Firefox.

I should add I know it say this in the README.md  but is there a way to prevent it?

Firefox 44.0

**Comment by mjanser** [comment]
It seems that the `search` function behaves a little bit weird in this case. I'll try to have a look later this week.

**Comment by mjanser** [comment]
I updated the add-on to hopefully fix this issue.

**Comment by jasonkuehl** [comment]
Awesome. I will be able to test later on this week.

Thank you @mjanser !
Jason.

**Comment by birdeee** [comment]
unfortunately (at least for me) the new code now does not remove the old bookmarks at all. every sync they get duplicated.
but i think i have fixed it locally by simply changing line 68 of index.js to
return item.type == "bookmark" && item.group.id == group.id;
(compare the group id and not the group object)

**Comment by theScrabi** [comment]
@birdeee could you plese make a pull request out of you fix :)

**Comment by mjanser** [comment]
Added the fix of @birdeee in 9b60f18b71fbb46d2caef79ae4c86d591be990a0 and submitted a new version.
