### ISSUE TITLE
Nothing gets synced running Owncloud 8.2.3, Bookmarks 0.7.1, Firefox 45

### ISSUE THREAD

**Issue by e-alfred** [mjanser/firefox-addon-owncloud-bookmarks#2]
Hello,

I am running Firefox 45 and the Bookmarks extension 0.0.2, my server runs Owncloud 8.2.3 and Bookmarks app 0.7.1. I have a valid SSL certificate, but if I click on the "Synchronize now" button, nothing happens. The bookmark folder is not created in Firefox and no error shows up on the browser console in Firefox (at least nothing releated to the extension). I cannot see anything in the Owncloud log file either. Is there anywhere I can look for something? I am running Owncloud on a custom port as well.

If I enter the full URL of the api I get a full list of all bookmarks in the browser i. e. appending this line with my username and password to the URL of my Owncloud instance: 

`https://mydomain:4545/index.php/apps/bookmarks/public/rest/v1/bookmark?user=myuser&password=mypass&select[0]=tags&select[1]=description"`

Thank you

**Comment by mjanser** [comment]
That's strange because the creation of the bookmark folder is the first thing the add-on does after some checks. If one of the checks fails this should be visible in the "Browser Console" of Firefox as type "Logging". Did you look at that?

Did you change the name of the bookmark folder? If yes can you test it with another name?

**Comment by e-alfred** [comment]
Yes, I also tried to change the bookmark folder, but it won't be created either if I press "Synchronize now". I tried it on different Firefox installations and nowhere is the bookmark folder created either. The only thing I get on the console is this but I do not know whether this belongs to the extension:

A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Sat Apr 02 2016 20:22:36 GMT+0200 (CEST)
Full Message: RequirementError: The `title` property must be defined.
Full Stack: JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: PendingErrors.register :: line 191
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.completePromise :: line 714
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: Handler.prototype.process :: line 969
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.walkerLoop :: line 812
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.scheduleWalkerLoop/< :: line 746 <unknown>

**Comment by mjanser** [comment]
This looks similar to #6 and should be fixed in the latest version.
