### ISSUE TITLE
Duplicates all bookmarks with OC 9.0.2 on CentOs 7 using Firefox 44.0, Windows 7 Enterprise 64-bit

### ISSUE THREAD

**Issue by milesgillham** [mjanser/firefox-addon-owncloud-bookmarks#4]
Every time the addon runs it adds an entire set of bookmarks. That is, if I have 12 bookmarks then on re-running I have 24 - 12 repeated. Doesn't seem to know what's already been synced.

Tried to workaround by setting refresh interval to 0 and then manually loading after deleting the bookmarks but this made it even worse.

Regards, Miles

**Comment by theScrabi** [comment]
I forked this project in order to work on this problem. So far I didn't find time to do so.

**Comment by mjanser** [comment]
This could be the same problem as in https://github.com/mjanser/firefox-addon-owncloud-bookmarks/issues/1#issuecomment-224564575. I added the provided fix and submitted a new version.

**Comment by mjanser** [comment]
I deprecated this add-on in favor of https://addons.mozilla.org/de/firefox/addon/floccus.
