### ISSUE TITLE
URIError: malformed URI sequence

### ISSUE THREAD

**Issue by omocinteractive** [mjanser/firefox-addon-owncloud-bookmarks#7]
... how can get the wrong URI? is there any debug information for me? manually all bookmarks are show.

15:50:34.413 owncloud-bookmarks:URIError: malformed URI sequence
Stack-Trace:
syncBookmarks/</</</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://owncloud-bookmarks/index.js:101:30
syncBookmarks/</</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://owncloud-bookmarks/index.js:94:17
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
commitComplete@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/places/bookmarks.js:164:5
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:750:11
1 core.js:106

**Comment by mjanser** [comment]
This looks like it can't decode a bookmark's URL. Maybe you have bookmarks which are wrongly encoded or the ownCloud bookmarks app does something wrong.

**Comment by omocinteractive** [comment]
It is possible to find out which URI is malformed? Is there a possibility to debug?

**Comment by mjanser** [comment]
You could try the [Add-on Debugger](https://developer.mozilla.org/en-US/Add-ons/Add-on_Debugger) to find out which URL is malformed. Another option would be to go to `/index.php/apps/bookmarks/public/rest/v1/bookmark?user={username}&password={password}&select[0]=tags&select[1]=description` on your ownCloud instance and try to decode the listed bookmarks using a tool like http://www.urldecoder.org/.

**Comment by omocinteractive** [comment]
it is possible that you tell me how you check the syntax for a link? i have 2500 bookmarks and don't get "happy" with the debugger. urldecoder.org need a format like http%3A%2F%2Fwww.test.com ... all about: ftp: help: etc. are deleted ...

**Comment by mjanser** [comment]
I deprecated this add-on in favor of https://addons.mozilla.org/de/firefox/addon/floccus.
