### ISSUE TITLE
Password transmitted in URL

### ISSUE THREAD

**Issue by ionum** [mjanser/firefox-addon-owncloud-bookmarks#9]
Your addons seems to transmit user password by GET-Request:

index.php/apps/bookmarks/public/rest/v1/bookmark?user=******&password=******&select[0]=tags&select[1]=description

This is highly insecure

Version: 0.0.6

**Comment by mjanser** [comment]
Thanks for your report. That was the only possible way to do it before the bookmarks app got updated recently.

I deprecated this add-on in favor of https://addons.mozilla.org/de/firefox/addon/floccus.
